name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: sachsom95/project_cs_v2@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
